export const Types = [
  {
    id: 1,
    name: 'normal',
    bg_color: '#c5c9d6',
    bg_type: ' #9da0aa',
  },
  {
    id: 2,
    name: 'fighting',
    bg_color: '#eb4971',
    bg_type: '#d04164',
  },
  {
    id: 3,
    name: 'flying',
    bg_color: '#829edb',
    bg_type: '#748fc9',
  },
  {
    id: 4,
    name: 'poison',
    bg_color: '#bd5fe9',
    bg_type: '#a552cc',
  },
  {
    id: 5,
    name: 'ground',
    bg_color: '#f78551',
    bg_type: '#dd7748',
  },
  {
    id: 6,
    name: 'rock',
    bg_color: '#d5c895',
    bg_type: '#baab82',
  },
  {
    id: 7,
    name: 'bug',
    bg_color: '#8bd674',
    bg_type: '#8cb230',
  },
  {
    id: 8,
    name: 'ghost',
    bg_color: '#6882d4',
    bg_type: '#556aae',
  },
  {
    id: 9,
    name: 'steel',
    bg_color: '#4d92b4',
    bg_type: '#417d9a',
  },
  {
    id: 10,
    name: 'fire',
    bg_color: '#ff9448',
    bg_type: '#fd7d24',
  },
  {
    id: 11,
    name: 'water',
    bg_color: '#58abf6',
    bg_type: '#4a90da',
  },
  {
    id: 12,
    name: 'grass',
    bg_color: '#8bbe8a',
    bg_type: '#62b957',
  },
  {
    id: 13,
    name: 'electric',
    bg_color: '#f2cb55',
    bg_type: '#eed535',
  },
  {
    id: 14,
    name: 'psychic',
    bg_color: '#ff787a',
    bg_type: '#ea5d60',
  },
  {
    id: 15,
    name: 'ice',
    bg_color: '#6bddce',
    bg_type: '#61cec0',
  },
  {
    id: 16,
    name: 'dragon',
    bg_color: '#1582e7',
    bg_type: '#0f6ac0',
  },
  {
    id: 17,
    name: 'dark',
    bg_color: '#75747e',
    bg_type: '#58575f',
  },
  {
    id: 18,
    name: 'fairy',
    bg_color: '#e98acc',
    bg_type: '#58575f',
  },
];
